#!/bin/bash
# Tolua++ script

cd `dirname $0`/../source/lua_bindings

TOLUAPP="../../vendor/install/bin/toluapp"

for f in $( find . -name '*.pkg' -print ); do
	PKG=`basename ${f%.*}`
	echo "Processing $PKG package..."
	$TOLUAPP -n $PKG \
		-o $PKG.cpp \
		-H $PKG.h \
		$f
done
